// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTypechoMeta = "typecho_metas"

// TypechoMeta mapped from table <typecho_metas>
type TypechoMeta struct {
	Mid         int32  `gorm:"column:mid;primaryKey;autoIncrement:true" json:"mid"`
	Name        string `gorm:"column:name" json:"name"`
	Slug        string `gorm:"column:slug" json:"slug"`
	Type        string `gorm:"column:type;not null" json:"type"`
	Description string `gorm:"column:description" json:"description"`
	Count       int32  `gorm:"column:count" json:"count"`
	Order       int32  `gorm:"column:order" json:"order"`
	Parent      int32  `gorm:"column:parent" json:"parent"`
}

// TableName TypechoMeta's table name
func (*TypechoMeta) TableName() string {
	return TableNameTypechoMeta
}
