// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTypechoContent = "typecho_contents"

// TypechoContent mapped from table <typecho_contents>
type TypechoContent struct {
	Cid          int32  `gorm:"column:cid;primaryKey;autoIncrement:true" json:"cid"`
	Title        string `gorm:"column:title" json:"title"`
	Slug         string `gorm:"column:slug" json:"slug"`
	Created      int32  `gorm:"column:created" json:"created"`
	Modified     int32  `gorm:"column:modified" json:"modified"`
	Text         string `gorm:"column:text" json:"text"`
	Order        int32  `gorm:"column:order" json:"order"`
	AuthorID     int32  `gorm:"column:authorId" json:"authorId"`
	Template     string `gorm:"column:template" json:"template"`
	Type         string `gorm:"column:type;default:post" json:"type"`
	Status       string `gorm:"column:status;default:publish" json:"status"`
	Password     string `gorm:"column:password" json:"password"`
	CommentsNum  int32  `gorm:"column:commentsNum" json:"commentsNum"`
	AllowComment string `gorm:"column:allowComment;default:0" json:"allowComment"`
	AllowPing    string `gorm:"column:allowPing;default:0" json:"allowPing"`
	AllowFeed    string `gorm:"column:allowFeed;default:0" json:"allowFeed"`
	Parent       int32  `gorm:"column:parent" json:"parent"`
}

// TableName TypechoContent's table name
func (*TypechoContent) TableName() string {
	return TableNameTypechoContent
}
