// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTypechoRelationship = "typecho_relationships"

// TypechoRelationship mapped from table <typecho_relationships>
type TypechoRelationship struct {
	Cid int32 `gorm:"column:cid;primaryKey" json:"cid"`
	Mid int32 `gorm:"column:mid;primaryKey" json:"mid"`
}

// TableName TypechoRelationship's table name
func (*TypechoRelationship) TableName() string {
	return TableNameTypechoRelationship
}
